# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('middle_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('birthdate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=15)),
                ('last_name', models.CharField(max_length=25)),
                ('phone', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=60)),
                ('street', models.CharField(max_length=40)),
                ('apt', models.CharField(max_length=6)),
                ('city', models.CharField(max_length=25)),
                ('state', models.CharField(max_length=2)),
                ('zipcode', models.IntegerField()),
                ('status', models.CharField(default='pending', max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='parent',
            field=models.ManyToManyField(related_name='child', to='loginreg.User'),
        ),
    ]
